apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: cnatest
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: skcc10130acr.azurecr.io/app:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: api.url.pay
              valueFrom:
                configMapKeyRef:
                  name: sidedish-config
                  key: api.url.pay
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m

---

apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: cnatest
  labels:
    app: app
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: app