apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: cnatest
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: skcc10130acr.azurecr.io/app:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: api.url.pay
              valueFrom:
                configMapKeyRef:
                  name: sidedish-config
                  key: api.url.pay

---

apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: cnatest
  labels:
    app: app
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: app